### ISSUE TITLE
frdroid version anytime soon?

### ISSUE THREAD

**Issue by 0lm** [Somethingweirdhere/Secure-Photo-Viewer#11]
sorry if this is annoying, but is there a chance to get the f-droid version of this app updated any time soon? normally im  patient because i know it takes a bit longer for fdroid. but in some cases the app authors had mistakes in their code given to fdroid so it coldnt be compiled or some versioning errors. and they didnt check it until some people mentioned that as issues.
so sometimes there is an error, why fdroid version of apps werent built yet. so just wanted to ask if you could check if there was any error so fdroid couldnt build it yet/or if you forgot to provide it for fdroid until now.

greetings

ps: i love this app. so useful when giving your phone to friends to show them stuff.

**Comment by Somethingweirdhere** [comment]
Hello! Sorry for the delay. I checked and there seems to be nothing wrong with the code itself. Usually someone updates it there quite quickly, but I don't think there is much I can do to speed it up. If you don't want to use the PlayStore version, you could for now download it from the [release page](https://github.com/Somethingweirdhere/Secure-Photo-Viewer/releases)

**Comment by 0lm** [comment]
thanks for the reply. and thanks for checking it. if there is nothing wrong then all i can do is wait. i will try to install the github release then. is the signature form github release the same as in fdroid? as far as i know, goggle play version has another signature than fdroid. well i think i will find out now.

greetings

**Comment by kanink007** [comment]
hello
its me again. i forgot to answer here after installing the github apk version of the app. somhow there is an error with versioning i think. because after installing the github version of the app, my yalpstore still says there is an update for the app.  it says: update v 1.3 (4 --> 5).
not sure why. and yeah the fdroid version is still not built, while other apps already got updates in fdroid.
just wanted to notify you.

greetings.

**Comment by Somethingweirdhere** [comment]
Oh geez you are totally right. I checked if it compiles, but I never actually pushed the version number to GitHub. No wonder it didn't get released on FDroid. I have now updated the source code and the APK. I just wonder if I have to delete the old release and make a new one, or if updating it was enough.

And thanks again for noticing that, I really missed it.

**Comment by kanink007** [comment]
hello there
im glad it could be solved, thanks for checking it a second time and fixing it. youre welcome. everything worked fine now. fdroid version is updated and yalpstoe doesnt pop up any new updates anymore.
greetings

**Comment by Somethingweirdhere** [comment]
Amazing! I will close the issue then :)
