### ISSUE TITLE
Please update this app for newer android 

### ISSUE THREAD

**Issue by RaWolFoX** [Somethingweirdhere/Secure-Photo-Viewer#20]
Please bring back this useful app.

**Comment by cyb3rko** [comment]
Thought the same, I've done some updates in my fork: https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.0  
I did not invest a lot of time, maybe I will publish it to F-Droid and GPlay in the future and make some more updates.  
Feedback is appreciated :)

**Comment by RaWolFoX** [comment]
> Thought the same, I've done some updates in my fork: https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.0  
> I did not invest a lot of time, maybe I will publish it to F-Droid and GPlay in the future and make some more updates.  
> Feedback is appreciated :)

Good to know👍🏻

**Comment by RaWolFoX** [comment]
> Thought the same, I've done some updates in my fork: https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.0  
> I did not invest a lot of time, maybe I will publish it to F-Droid and GPlay in the future and make some more updates.  
> Feedback is appreciated :)

Hey. Can you make it full screen. Its not using whole screen. Status bar is hiding but that area is not used. There is a black bar on top side.

![look here](https://github.com/gregordr/Secure-Photo-Viewer/assets/114433842/8531d682-e786-4571-8f56-0d94cac7a2f8)

**Comment by cyb3rko** [comment]
For feedback about my version of this app, please open issues over at https://github.com/cyb3rko/Secure-Photo-Viewer.

**Comment by Korb** [comment]
Currently [the app page in F-Droid](https://f-droid.org/en/packages/com.gtp.showapicturetoyourfriend/) displays a warning when viewed on Google Android 14

> This app was built for an older version of Android and cannot be updated automatically.

> OS version: Funtouch OS 14
> Model: Vivo T1 (4G) / V2153
> Hardware version: MP_0.1
> Build number: PD22010F_EX_A_14.2.7.2.W20
> Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.71
> Kernel version: 4.19.157-perf+ 1 Fri Mar 1 16:22:31 CST 2024
> Compile time: 1 Mar 2024 11:02:07
> Android security update: 1 March 2024
> Google Play system update: 1 April 2024

**Comment by cyb3rko** [comment]
@Korb That is the official app from https://github.com/gregordr/Secure-Photo-Viewer.  
This here is a fork to update this app to update it's dependencies and make it work again.
