### ISSUE TITLE
Translation pt-br

### ISSUE THREAD

**Issue by hanelore** [Somethingweirdhere/Secure-Photo-Viewer#4]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by Somethingweirdhere** [comment]
Hello and thanks for your help!

Apps are supposed to have all their strings in one file, so they can be easily translated. I have now done that, and started out with the german translation.

I am working on a new play store description too, and currently trying the segmentation test feature. When I am finished with that, I would appreciate if you could help me translate that as well :)

**Comment by Somethingweirdhere** [comment]
I merged it and made a new release. It should be on the play store in the next few days. Thanks again!

Incase you also want to help translating the Play Store descriptions, here they are:

Short description: 

> Protect your gallery from nosy eyes

Long description:

> Have you ever handed over your phone to someone else to show them cool photo, selfie, or the latest meme? Did someone ever scroll too far through your gallery and saw something they weren't supposed to see? Or they took your unlocked phone and did something else?
> 
> Now there is a simple solution: Select the pictures and videos you want them to see, press share and select the Secure Photo Viewer! Now they can only see the selected photos, while everything else, including the rest of your gallery is protected by your usual lockscreen. It's an easy and effective way to protect your privacy from your friends.
> 
> This app is private and secure. There are no adds, and no data is ever sent. The source code can be found here: https://github.com/Somethingweirdhere/Secure-Photo-Viewer


Of course, feel free to make any adjustments you feel like are needed.

**Comment by hanelore** [comment]
Thanks @Somethingweirdhere 

Here is the Play Store translation **(pt-br)**:

### Short description:

> "Proteja sua galeria de curiosos"

### Long description:

> "Voce já entregou seu celular para alguém para mostrar aquela foto bacana, selfie ou o último meme de sucesso? Nessa situação, alguém já excedeu os limites olhando muito mais que o permitido na sua galeria? Ou então pegaram seu celular desbloqueado e fizeram algo mais?

Agora temos uma solução: Selecione as fotos e os vídeos que voce deseja que eles vejam, aperte a opção de compartilhar e selecione o Secure Photo Viewer! Agora eles podem ver somente as fotos selecionadas por voce, enquanto o restante da galeria estará protegido com a trava de tela. É uma maneira fácil e efetiva de proteger sua privacidade dos seus amigos.

Esse app é privado e seguro. Não há propagandas muito menos envio metadados. O código fonte encontra-se aqui:https://github.com/Somethingweirdhere/Secure-Photo-Viewer"

In the Play Store [web page](https://play.google.com/store/apps/details?id=com.gtp.showapicturetoyourfriend), Google Translator is enable:

![image](https://user-images.githubusercontent.com/40754811/47455006-12387400-d7a7-11e8-8e56-6ba805b8e5cf.png)


PR sent: https://github.com/Somethingweirdhere/Secure-Photo-Viewer/pull/10/commits/7dc6c47e502fd02dc858287d8fb20403c9f8c2f0
