### ISSUE TITLE
crash after 1.2 version update on Oct, 20th  

### ISSUE THREAD

**Issue by lgasp** [Somethingweirdhere/Secure-Photo-Viewer#8]
After update the application crashes when tapping the "view" button and doesn't show the pics if I lock the phone.
It looks to me like it doesn't load the puctures

**Comment by Somethingweirdhere** [comment]
Yes, I have forgotten to remove something... it was really stupid.

I have just released a new release here, and an update on the play store. 
I'm really sorry for this.

**Comment by lgasp** [comment]
Don't worry, errors happen all the time. 
Anyway, thank you for the useful app!
