### ISSUE TITLE
Black screen display

### ISSUE THREAD

**Issue by GIPeon** [Somethingweirdhere/Secure-Photo-Viewer#9]
Hey there!

Your app looked exactly what I needed, unfortunately I can't make it work. :(

I can select and share the pics, but then after the screen saying tap on view or lock the screen, it just goes black with only the back button visible. What can I do to help you debug it?

I'm using a an Android 6.0 encrypted with no root, password locked. Also usually the pictures are stored in an external SD card, but AFAIK the app has storage permission enabled. APK from fdroid version 1.3.

Thank you!

**Comment by Somethingweirdhere** [comment]
Hello!

Sorry to see that you are having an issue. I haven't heard of that one in particular yet, so let's see what can be done.

>  AFAIK the app has storage permission enabled
Can you make sure? (Go to settings, apps, Secure Photo Viewer, Permissions) That would be the easiest fix. 

Also, have you already tried reinstalling the app?

Also, could you provide a screenshot? I'm a bit confused by the back button. There usually isn't one, unless you mean the one on the bottom of the phone. But then, the switch-apps button on the other side should be visible too?

What app are you using to share? Are there any pictures that the app works with?

If you open firefox or chrome, and long-press any image for example, can you share it then and does it work?

**Comment by GIPeon** [comment]
Hei there!
Yes the permission is enabled, and I found the issue I think. Your suggestion to use a browser worked nicely, so I suspected that there was something else dealing with the images I was trying to open in your app. Basically pictures located in the external micro SD are not displayed, so what you get is the black screen I told you. Unfortunately screenshots are not very helpfull because they are totally black :| and the on screen back button is not visible (Btw I can't se the square or circle button for home in your app viewer, only the back button; probably because I'm enabling the viewer by locking the screen with pin).

So I can open correctly pictures located in the internal SD storage, but not the external SD card. IIRC this is a kind of common issue with android 6, but I'm not really an expert. You think there is something that can be done to make it available also for external SD content?

Thank you for your time!

**Comment by Somethingweirdhere** [comment]
That's weird. I can't reproduce it on my phone, nor does it happen on the emulator. I will try some googling around what might be the issue. I know that since Android 6 we need to request runtime permissions, but haven't yet heard of an SD card issue.

Anyways, for now, all I can suggest is putting the files onto the internal storage?

Also, I have made another version that asks for Write and read storage. Not sure it makes a difference, but it may be worth a try:
[app-debug.zip](https://github.com/Somethingweirdhere/Secure-Photo-Viewer/files/2513527/app-debug.zip)

You need to rename it to an .apk and then make sure the Dialog that asks for permissions comes up.

Again, sorry for this issue.

**Comment by GIPeon** [comment]
Thank you for your time in this, and really don't be sorry, it's a great app (incredible none have did anything similar before, I wasn't able to find it in the play store!), it's open source and it's free, really the least I can do is to say thank you and report possible issue like this and maybe try to help debug it (unfortunately I'm no Android nor Java dev!).

Luckily enough I found (hopefully!) the core issue. While fiddling few tests with the updated apk, I found a couple images that were working correctly also on my ext SD card. I looked for possible folder permission issues or similar, then I noticed that the pictures where very small in pixel size (800x900). On my sd card most of the pictures are from my phone camera with a general resolution of 12+MB, usally with at least one side with 4k+ pixels. That's the core issue (at least on my phone). 

Any picture with a size larger than 4000 px is not displayed. 

Try with the 2 following pics, one is 4000x3000 the other 400**1**x3000. Here is [4000](https://user-images.githubusercontent.com/34616429/47547040-66e10980-d8e3-11e8-96c3-b57581b162ad.jpg). This is [4001](https://user-images.githubusercontent.com/34616429/47547058-719b9e80-d8e3-11e8-9b0e-2b4d4c53d2e9.jpg)

This is valid with any app  (browser, default img viewer etc...) and in any location (local storage or external sd card).

Let me know if you can reproduce this! Thank you!

**Comment by Somethingweirdhere** [comment]
That's really intersting. I can't reproduce it, but I will try with an emulator with less Ram, or with an even bigger picture. By the way, is the picture you uploaded 680 KB big? If not, then the website has compressed it.

>It also should display toast messages that say what the app is reading, which would help me know where it messes up.
And could you tell me the Toasts that come up when you do a working 4000px image and when you do a non-working 4001px image?

>This is valid with any app (browser, default img viewer etc...) and in any location (local storage or external sd card). 

So it has nothing to do with the SD card at all? Also, that means the app you share it from doesn't matter, right?

**Comment by GIPeon** [comment]
> That's really intersting. I can't reproduce it, but I will try with an
emulator with less Ram, or with an even bigger picture. By the way, is the
picture you uploaded 680 KB big? If not, then the website has compressed it.

Yea the pictures uploaded are roughly 600kb big, I thought also could have
been a ram size issue, but I was able to open pictures up to 4000px of 5/6
MBytes without issues, anyway my phone has 2gb ram, usually free is less
than 1.2/1.3. If you need some hardware or other specs let me know.

> And could you tell me the Toasts that come up when you do a working
4000px image and when you do a non-working 4001px image?

Sorry forgot to tell you about it, nothing special I think, it just buble
up with "Image" written.

> So it has nothing to do with the SD card at all? Also, that means the app
you share it from doesn't matter, right?

Yes, I thought that maybe the encryption process of my phone had something
to do with it but I guess not atm.

**Comment by Somethingweirdhere** [comment]
Alright, it doesn't happen with your photo, but if I take a 16k photo it does. So maybe it's dependant on the screen size or screen resolution? Anyways, I will look into it.

**Comment by GIPeon** [comment]
Well that's interesting! I remember this kind of quirks used to happen also for web contents, where basically you had to stick with images size not larger than 2000 pixels or so... thank you!

**Comment by Somethingweirdhere** [comment]
Hey! I changed a bit how the imaged are sized. Ideally, the 2000.apk should work. If not, please also try the 1000. If any of them work,, it would be great if you could tell me if you can notice any quality or performance loss in comparison to earlier versions (with the pictures that did work).

[2000.zip](https://github.com/Somethingweirdhere/Secure-Photo-Viewer/files/2522008/2000.zip)
[1000.zip](https://github.com/Somethingweirdhere/Secure-Photo-Viewer/files/2522009/1000.zip)

**Comment by Somethingweirdhere** [comment]
Any update on this?

**Comment by GlassGruber** [comment]
Hey there, sorry for the late reply!
As of now the 1000 apk looks like working correctly as far as I can tell. The 2000 instead got it twisted up: I was able only to open small weight images, but nothing with few MB in weight, 4k px or lower.

So I guess it's fixed! :tada:

**Comment by Somethingweirdhere** [comment]
Very well!
